server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/corporate_portal
spring.datasource.username=mm_app
spring.datasource.password=9458

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.default_schema=mm
spring.jpa.open-in-view=false

spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.time-zone=UTC

jwt.secret=DpLmHXXxFrgPP7M+G76naslpGE4IL4RvU+h9MPNtsZI=
jwt.expiration-seconds=86400

app.idle.sweeperMs=5000
app.idle.inactivityMinutes=5
app.idle.confirmationGraceSeconds=15

files.documents-dir=C:/meowmeow_docs
documents.storage.path=C:\\meowmeow_docs